Repository citra-emu/citra, pull requests merged in 2018-03, with the labels that each got.

#3441 Service/FS: convert to ServiceFramework
  src/core/file_sys/archive_backend.cpp
  src/core/file_sys/archive_backend.h
  src/core/hle/ipc_helpers.h
  src/core/hle/service/fs/archive.cpp
  src/core/hle/service/fs/archive.h
  src/core/hle/service/fs/fs_user.cpp
  src/core/hle/service/fs/fs_user.h
  src/core/hle/service/service.cpp
Labels: canary-merge

#3462 Service/AM: convert to ServiceFramework
  src/core/hle/ipc_helpers.h
  src/core/hle/service/am/am.cpp
  src/core/hle/service/am/am.h
  src/core/hle/service/am/am_app.cpp
  src/core/hle/service/am/am_app.h
  src/core/hle/service/am/am_net.cpp
  src/core/hle/service/am/am_net.h
  src/core/hle/service/am/am_sys.cpp
  src/core/hle/service/am/am_sys.h
  src/core/hle/service/am/am_u.cpp
  src/core/hle/service/am/am_u.h
  src/core/hle/service/fs/fs_user.cpp
  src/core/hle/service/service.cpp
Labels: canary-merge

#3444 UDS: Add non zero mac address to the shared page
  src/core/hle/service/nwm/nwm.cpp
  src/core/hle/shared_page.cpp
  src/core/hle/shared_page.h
Labels: canary-merge

#3440 File_Sys: Add a size dependent delay for each file read
  src/core/CMakeLists.txt
  src/core/file_sys/archive_extsavedata.cpp
  src/core/file_sys/archive_ncch.cpp
  src/core/file_sys/archive_ncch.h
  src/core/file_sys/archive_sdmc.cpp
  src/core/file_sys/archive_selfncch.cpp
  src/core/file_sys/delay_generator.h
  src/core/file_sys/disk_archive.h
  src/core/file_sys/file_backend.h
  src/core/file_sys/ivfc_archive.cpp
  src/core/file_sys/ivfc_archive.h
  src/core/file_sys/savedata_archive.cpp
  src/core/hle/service/fs/archive.cpp
Labels: canary-merge

#3281 Texture Cache Rework
  src/citra/config.cpp
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/configure_graphics.cpp
  src/common/math_util.h
  src/core/frontend/framebuffer_layout.cpp
  src/core/frontend/framebuffer_layout.h
  src/core/hle/kernel/vm_manager.cpp
  src/core/hle/service/gsp/gsp_gpu.cpp
  src/core/hw/gpu.cpp
  src/core/memory.cpp
  src/core/memory.h
  src/core/settings.h
  src/tests/core/arm/arm_test_common.cpp
  src/video_core/rasterizer_interface.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
  src/video_core/renderer_opengl/gl_resource_manager.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/swrasterizer/swrasterizer.h
  src/video_core/utils.h
Labels: canary-merge, pr:reviewed

#3469 Service/FRD: convert to ServiceFramework
  src/core/hle/ipc_helpers.h
  src/core/hle/service/frd/frd.cpp
  src/core/hle/service/frd/frd.h
  src/core/hle/service/frd/frd_a.cpp
  src/core/hle/service/frd/frd_a.h
  src/core/hle/service/frd/frd_u.cpp
  src/core/hle/service/frd/frd_u.h
  src/core/hle/service/service.cpp
Labels: canary-merge

#3486 Discard Gas mode renders
  src/video_core/renderer_opengl/gl_shader_gen.cpp
Labels: canary-merge

#3470 Service/NEWS: convert to ServiceFramework
  src/core/hle/service/news/news.cpp
  src/core/hle/service/news/news.h
  src/core/hle/service/news/news_s.cpp
  src/core/hle/service/news/news_s.h
  src/core/hle/service/news/news_u.cpp
  src/core/hle/service/news/news_u.h
  src/core/hle/service/service.cpp
Labels: canary-merge

#3476 Service/NFC: convert to ServiceFramework
  src/core/hle/service/nfc/nfc.cpp
  src/core/hle/service/nfc/nfc.h
  src/core/hle/service/nfc/nfc_m.cpp
  src/core/hle/service/nfc/nfc_m.h
  src/core/hle/service/nfc/nfc_u.cpp
  src/core/hle/service/nfc/nfc_u.h
  src/core/hle/service/service.cpp
Labels: canary-merge

#3071 Network: Added an executable to host an dedicated room for local wifi
  .travis/linux/upload.sh
  .travis/macos/upload.sh
  src/CMakeLists.txt
  src/dedicated_room/CMakeLists.txt
  src/dedicated_room/citra-room.cpp
  src/dedicated_room/citra-room.rc
Labels: canary-merge

#3498 Service/CFG: convert to ServiceFramework
  src/citra_qt/configuration/configure_system.cpp
  src/citra_qt/configuration/configure_system.h
  src/core/hle/ipc_helpers.h
  src/core/hle/service/apt/applet_manager.cpp
  src/core/hle/service/apt/apt.cpp
  src/core/hle/service/cfg/cfg.cpp
  src/core/hle/service/cfg/cfg.h
  src/core/hle/service/cfg/cfg_i.cpp
  src/core/hle/service/cfg/cfg_i.h
  src/core/hle/service/cfg/cfg_nor.cpp
  src/core/hle/service/cfg/cfg_nor.h
  src/core/hle/service/cfg/cfg_s.cpp
  src/core/hle/service/cfg/cfg_s.h
  src/core/hle/service/cfg/cfg_u.cpp
  src/core/hle/service/cfg/cfg_u.h
  src/core/hle/service/service.cpp
  src/core/loader/ncch.cpp
Labels: canary-merge

#3528 use nvidia graphics automatically on laptops with optimus
  src/citra/citra.cpp
  src/citra_qt/main.cpp
Labels: canary-merge

#3484 pica/lighting: compute highlight clamp after one-/two-sided diffuse pass
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/swrasterizer/lighting.cpp
Labels: canary-merge

#3481 NWM_UDS:: Check flags in SendTo
  src/core/hle/service/nwm/nwm_uds.cpp
  src/network/room.h
  src/network/room_member.h
Labels: canary-merge

#3172 appveyor: Generate PDBs for mingw build
  .appveyor/FindDependencies.ps1
  .appveyor/ProcessPdb.ps1
  CMakeLists.txt
  appveyor.yml
Labels: pr:needs-review
