Repository citra-emu/citra, pull requests merged in 2019-09, with the labels that each got.

#4894 opengl: remove hw geometry shader related stuff
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
  src/video_core/renderer_opengl/gl_shader_decompiler.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_shader_manager.h
Labels: canary-merge

#4896 citra_qt: Misc game list updates/fixes
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/configure_ui.cpp
  src/citra_qt/configuration/configure_ui.ui
  src/citra_qt/game_list.cpp
  src/citra_qt/game_list_p.h
  src/citra_qt/uisettings.h
  src/core/loader/smdh.cpp
  src/core/loader/smdh.h
Labels: canary-merge

#4893 NFC: extract frontend-facing tag state
  src/core/hle/service/nfc/nfc.cpp
  src/core/hle/service/nfc/nfc.h
Labels: canary-merge

#4900 ncch_container: Fix NCCH decryption heuristic when replacing exheader
  src/core/file_sys/ncch_container.cpp
Labels: canary-merge, pr:pending-merge

#4922 Filter non-executable files out of the game list.
  src/citra_qt/game_list_worker.cpp
  src/core/loader/loader.h
  src/core/loader/ncch.cpp
  src/core/loader/ncch.h
Labels: canary-merge

#4917 Allow displaying the long_title of the game
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/configure_ui.ui
  src/citra_qt/game_list.cpp
  src/citra_qt/game_list_p.h
  src/citra_qt/uisettings.h
  src/core/loader/smdh.cpp
  src/core/loader/smdh.h
Labels: canary-merge

#4930 Pause when in background
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/configure_general.cpp
  src/citra_qt/configuration/configure_general.ui
  src/citra_qt/main.cpp
  src/citra_qt/main.h
  src/citra_qt/uisettings.h
Labels: canary-merge

#4847 core, citra_qt: IPC Recorder
  src/citra_qt/CMakeLists.txt
  src/citra_qt/debugger/ipc/record_dialog.cpp
  src/citra_qt/debugger/ipc/record_dialog.h
  src/citra_qt/debugger/ipc/record_dialog.ui
  src/citra_qt/debugger/ipc/recorder.cpp
  src/citra_qt/debugger/ipc/recorder.h
  src/citra_qt/debugger/ipc/recorder.ui
  src/citra_qt/main.cpp
  src/citra_qt/main.h
  src/core/CMakeLists.txt
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/hle_ipc.h
  src/core/hle/kernel/ipc.cpp
  src/core/hle/kernel/ipc.h
  src/core/hle/kernel/ipc_debugger/recorder.cpp
  src/core/hle/kernel/ipc_debugger/recorder.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/service/service.cpp
  src/core/hle/service/service.h
  src/core/hle/service/sm/sm.cpp
  src/core/hle/service/sm/sm.h
Labels: canary-merge, pr:needs-review
