Repository citra-emu/citra, pull requests merged in 2019-08, with the labels that each got.

#4859 minor fix for opengles
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer_cache.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
Labels: canary-merge

#4578 renderer_opengl: Add support for custom shaders
  src/citra/config.cpp
  src/citra/default_ini.h
  src/citra_qt/configuration/config.cpp
  src/citra_qt/configuration/configure_graphics.cpp
  src/citra_qt/configuration/configure_graphics.h
  src/citra_qt/configuration/configure_graphics.ui
  src/common/common_paths.h
  src/common/file_util.cpp
  src/common/file_util.h
  src/core/frontend/emu_window.cpp
  src/core/hle/kernel/shared_page.cpp
  src/core/hle/kernel/shared_page.h
  src/core/settings.cpp
  src/core/settings.h
  src/core/telemetry_session.cpp
  src/video_core/CMakeLists.txt
  src/video_core/renderer_opengl/post_processing_opengl.cpp
  src/video_core/renderer_opengl/post_processing_opengl.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
  src/video_core/video_core.cpp
  src/video_core/video_core.h
Labels: canary-merge, pr:needs-review

#4866 configure_dialog: reverse tab map to avoid logic based on user-facing/translatable text
  src/citra_qt/configuration/configure_dialog.cpp
Labels: canary-merge

#4703 [EXPERIMENT] gl_rasterizer: decrease vertex buffer size
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: canary-merge

#4844 Use a clear texture instead of texture 0 (solid black) in the GL rasterizer
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
Labels: canary-merge

#4846 Fix incorrect display of some Taiwan region games
  src/core/loader/smdh.cpp
Labels: pr:needs-work

#4602 Implement dumping audio+video to video files
  .travis.yml
  .travis/linux-frozen/docker.sh
  .travis/linux-mingw/docker.sh
  .travis/linux/docker.sh
  CMakeLists.txt
  CMakeModules/CopyCitraFFmpegDeps.cmake
  appveyor.yml
  src/audio_core/CMakeLists.txt
  src/audio_core/dsp_interface.cpp
  src/citra/citra.cpp
  src/citra_qt/CMakeLists.txt
  src/citra_qt/configuration/config.cpp
  src/citra_qt/main.cpp
  src/citra_qt/main.h
  src/citra_qt/main.ui
  src/citra_qt/ui_settings.h
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/core.h
  src/core/dumping/backend.cpp
  src/core/dumping/backend.h
  src/core/dumping/ffmpeg_backend.cpp
  src/core/dumping/ffmpeg_backend.h
  src/video_core/renderer_base.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
Labels: canary-merge, pr:needs-review

#4862 ncch_container: Assume override exheaders are decrypted
  src/core/file_sys/ncch_container.cpp
Labels: canary-merge, pr:reviewed

#4472 HLE: Move NS:S into APT and remove NS
  src/core/CMakeLists.txt
  src/core/hle/service/apt/applet_manager.cpp
  src/core/hle/service/apt/apt.cpp
  src/core/hle/service/apt/apt.h
  src/core/hle/service/apt/apt_a.cpp
  src/core/hle/service/apt/apt_a.h
  src/core/hle/service/apt/apt_s.cpp
  src/core/hle/service/apt/apt_s.h
  src/core/hle/service/apt/apt_u.cpp
  src/core/hle/service/apt/apt_u.h
  src/core/hle/service/apt/ns.cpp
  src/core/hle/service/apt/ns.h
  src/core/hle/service/apt/ns_s.cpp
  src/core/hle/service/apt/ns_s.h
  src/core/hle/service/service.cpp
Labels: pr:needs-review

#4885 Add MinGW CMake option to disable DWARF debugging information
  .travis/linux-mingw/docker.sh
  CMakeLists.txt
  src/CMakeLists.txt
Labels: canary-merge
