Repository citra-emu/citra, pull requests merged in 2020-02, with the labels that each got.

#5078 logging/backend: Change type of filename from string to const c…
  src/common/logging/backend.h
Labels: canary-merge

#5079 citra_qt: config: Move audio to its own tab.
  src/citra_qt/configuration/configure_dialog.cpp
Labels: canary-merge

#5069 Update minimum window size based on current layout
  src/citra_qt/bootmanager.cpp
  src/core/frontend/emu_window.cpp
  src/core/frontend/emu_window.h
  src/core/frontend/framebuffer_layout.cpp
  src/core/frontend/framebuffer_layout.h
Labels: canary-merge

#5077 Port yuzu-emu/yuzu#3339: "GUI: fix minor issues with dark themes + rename and reorder themes"
  dist/qt_themes/qdarkstyle/style.qss
  src/citra_qt/uisettings.cpp
Labels: canary-merge

#4754 HTTP_C::Implement Context::MakeRequest
  externals/CMakeLists.txt
  externals/android-ifaddrs/CMakeLists.txt
  externals/android-ifaddrs/ifaddrs.c
  externals/android-ifaddrs/ifaddrs.h
  externals/httplib/README.md
  externals/httplib/httplib.h
  src/core/CMakeLists.txt
  src/core/hle/service/http_c.cpp
  src/core/hle/service/http_c.h
  src/web_service/CMakeLists.txt
  src/web_service/web_backend.cpp
Labels: canary-merge, pr:needs-review

#4764 Implements fdk_aac decoder
  CMakeLists.txt
  src/audio_core/CMakeLists.txt
  src/audio_core/hle/fdk_decoder.cpp
  src/audio_core/hle/fdk_decoder.h
  src/audio_core/hle/hle.cpp
Labels: pr:needs-review, pr:needs-work

#5088 core/file_sys: LayeredFS support
  src/citra_qt/game_list.cpp
  src/citra_qt/game_list.h
  src/citra_qt/main.cpp
  src/citra_qt/main.h
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/file_sys/layered_fs.cpp
  src/core/file_sys/layered_fs.h
  src/core/file_sys/ncch_container.cpp
  src/core/file_sys/ncch_container.h
  src/core/file_sys/romfs_reader.cpp
  src/core/file_sys/romfs_reader.h
  src/core/loader/3dsx.cpp
  src/core/loader/loader.h
  src/core/loader/ncch.cpp
  src/core/loader/ncch.h
Labels: canary-merge, pr:pending-merge

#5111 video_core: use explicit interval type in texture cache
  src/video_core/renderer_opengl/gl_rasterizer_cache.h
Labels: canary-merge

#5103 core: Add support for N3DS memory mappings
  src/core/core.cpp
  src/core/core.h
  src/core/file_sys/ncch_container.h
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/memory.cpp
  src/core/loader/loader.h
  src/core/loader/ncch.cpp
  src/core/loader/ncch.h
  src/tests/core/arm/arm_test_common.cpp
  src/tests/core/hle/kernel/hle_ipc.cpp
  src/tests/core/memory/memory.cpp
Labels: canary-merge
