Repository citra-emu/citra, pull requests merged in 2023-08, with the labels that each got.

#6705 rasterizer_cache: Remove runtime allocation caching
  src/common/slot_vector.h
  src/core/core.cpp
  src/video_core/CMakeLists.txt
  src/video_core/rasterizer_cache/framebuffer_base.cpp
  src/video_core/rasterizer_cache/framebuffer_base.h
  src/video_core/rasterizer_cache/rasterizer_cache.h
  src/video_core/rasterizer_cache/rasterizer_cache_base.h
  src/video_core/rasterizer_cache/slot_id.h
  src/video_core/rasterizer_cache/surface_base.h
  src/video_core/rasterizer_cache/surface_params.cpp
  src/video_core/rasterizer_cache/surface_params.h
  src/video_core/rasterizer_cache/utils.h
  src/video_core/renderer_base.h
  src/video_core/renderer_opengl/frame_dumper_opengl.cpp
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_texture_mailbox.cpp
  src/video_core/renderer_opengl/gl_texture_mailbox.h
  src/video_core/renderer_opengl/gl_texture_runtime.cpp
  src/video_core/renderer_opengl/gl_texture_runtime.h
  src/video_core/renderer_opengl/renderer_opengl.cpp
  src/video_core/renderer_opengl/renderer_opengl.h
Labels: canary-merge

#6659 core: De-globalize movie
  src/android/app/src/main/jni/native.cpp
  src/audio_core/hle/hle.cpp
  src/citra/citra.cpp
  src/citra_qt/compatdb.cpp
  src/citra_qt/configuration/configure_storage.cpp
  src/citra_qt/debugger/wait_tree.cpp
  src/citra_qt/discord_impl.cpp
  src/citra_qt/discord_impl.h
  src/citra_qt/main.cpp
  src/citra_qt/movie/movie_play_dialog.cpp
  src/citra_qt/movie/movie_play_dialog.h
  src/citra_qt/movie/movie_record_dialog.cpp
  src/citra_qt/movie/movie_record_dialog.h
  src/core/core.cpp
  src/core/core.h
  src/core/file_sys/ncch_container.h
  src/core/hle/kernel/hle_ipc.cpp
  src/core/hle/kernel/kernel.cpp
  src/core/hle/kernel/kernel.h
  src/core/hle/kernel/memory.cpp
  src/core/hle/kernel/shared_page.cpp
  src/core/hle/kernel/shared_page.h
  src/core/hle/kernel/svc.cpp
  src/core/hle/kernel/vm_manager.h
  src/core/hle/service/act/act.cpp
  src/core/hle/service/apt/applet_manager.cpp
  src/core/hle/service/apt/apt.cpp
  src/core/hle/service/frd/frd.cpp
  src/core/hle/service/hid/hid.cpp
  src/core/hle/service/ir/extra_hid.cpp
  src/core/hle/service/ir/extra_hid.h
  src/core/hle/service/ir/ir_rst.cpp
  src/core/hle/service/ir/ir_user.cpp
  src/core/hle/service/nfc/nfc_device.cpp
  src/core/hle/service/nim/nim_u.cpp
  src/core/hle/service/service.cpp
  src/core/loader/loader.h
  src/core/loader/ncch.cpp
  src/core/movie.cpp
  src/core/movie.h
  src/core/savestate.cpp
  src/core/savestate.h
  src/core/telemetry_session.cpp
  src/tests/audio_core/hle/hle.cpp
  src/tests/audio_core/lle/lle.cpp
  src/video_core/custom_textures/custom_tex_manager.cpp
  src/video_core/renderer_opengl/gl_shader_disk_cache.cpp
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/pica_to_gl.h
  src/video_core/renderer_vulkan/vk_shader_gen.cpp
  src/video_core/renderer_vulkan/vk_shader_gen_spv.cpp
Labels: canary-merge

#6824 Move MiiData to its own namespace and add ChecksummedMiiData
  src/android/app/src/main/jni/applets/mii_selector.cpp
  src/citra_qt/applets/mii_selector.cpp
  src/citra_qt/applets/mii_selector.h
  src/core/CMakeLists.txt
  src/core/frontend/applets/mii_selector.cpp
  src/core/frontend/applets/mii_selector.h
  src/core/hle/applets/mii_selector.cpp
  src/core/hle/applets/mii_selector.h
  src/core/hle/mii.cpp
  src/core/hle/mii.h
  src/core/hle/service/nfc/amiibo_crypto.cpp
  src/core/hle/service/nfc/nfc_device.cpp
  src/core/hle/service/nfc/nfc_types.h
Labels: canary-merge

#6828 http/soc: Various implementations and fixes
  src/core/CMakeLists.txt
  src/core/core.cpp
  src/core/hle/service/ac/ac.cpp
  src/core/hle/service/cam/y2r_u.cpp
  src/core/hle/service/cam/y2r_u.h
  src/core/hle/service/err/err_f.cpp
  src/core/hle/service/err/err_f.h
  src/core/hle/service/http/http_c.cpp
  src/core/hle/service/http/http_c.h
  src/core/hle/service/mic/mic_u.cpp
  src/core/hle/service/mic/mic_u.h
  src/core/hle/service/service.cpp
  src/core/hle/service/soc/soc_u.cpp
  src/core/hle/service/soc/soc_u.h
  src/core/hle/service/ssl/ssl_c.cpp
  src/core/hle/service/ssl/ssl_c.h
  src/core/hw/y2r.cpp
Labels: canary-merge

#6837 cmake: fix `USE_SYSTEM_BOOST` behavior
  CMakeLists.txt
  externals/CMakeLists.txt
Labels: A-build-system, pr:needs-review

#6851 rasterizer_cache: Allow custom recycle
  src/video_core/rasterizer_cache/rasterizer_cache.h
  src/video_core/rasterizer_cache/rasterizer_cache_base.h
  src/video_core/rasterizer_cache/surface_base.h
  src/video_core/rasterizer_cache/surface_params.cpp
Labels: canary-merge

#6850 gl_texture_runtime: Implement ARB_clear_texture
  src/video_core/renderer_opengl/gl_texture_runtime.cpp
  src/video_core/renderer_opengl/gl_texture_runtime.h
Labels: canary-merge

#6867 qt: Fix double dialog and crash when OpenGL is selected on unsupported platform.
  src/citra_qt/main.cpp
Labels: canary-merge

#6864 http/ac: Fix failing assert and stub GetConnectingProxyEnable
  src/core/hle/service/ac/ac.cpp
  src/core/hle/service/ac/ac.h
  src/core/hle/service/ac/ac_i.cpp
  src/core/hle/service/ac/ac_u.cpp
  src/core/hle/service/http/http_c.cpp
Labels: canary-merge

#6875 qt: Only register graphics debugger as observer if visible.
  src/citra_qt/debugger/graphics/graphics.cpp
  src/citra_qt/debugger/graphics/graphics.h
Labels: canary-merge

#6863 qt: Update Qt to 6.5.1
  CMakeLists.txt
  CMakeModules/DownloadExternals.cmake
Labels: canary-merge

#6880 service/cecd: Fix buffer writes in ReadData.
  src/core/hle/service/cecd/cecd.cpp
Labels: canary-merge

#6845 build: Add flag for disabling bundling target.
  CMakeLists.txt
Labels: canary-merge

#6881 qt: Make input configuration scrollable.
  src/citra_qt/configuration/configure_input.ui
Labels: canary-merge

#6885 (gl/vk)_shader_gen: Use floor instead of int cast
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_vulkan/vk_shader_gen.cpp
  src/video_core/renderer_vulkan/vk_shader_gen_spv.cpp
Labels: canary-merge

#6879 opengl: disable ClearTexture on Intel drivers
  src/video_core/renderer_opengl/gl_driver.cpp
  src/video_core/renderer_opengl/gl_driver.h
  src/video_core/renderer_opengl/gl_texture_runtime.cpp
Labels: canary-merge

#6890 Fix post processing shaders crashing on Intel GPUs
  src/video_core/renderer_opengl/post_processing_opengl.cpp
Labels: canary-merge

#6878 renderer/vulkan: Emulate custom border colors in shaders when unavailable.
  CMakeModules/GenerateSCMRev.cmake
  src/video_core/rasterizer_accelerated.cpp
  src/video_core/rasterizer_accelerated.h
  src/video_core/renderer_vulkan/vk_instance.cpp
  src/video_core/renderer_vulkan/vk_shader_gen.cpp
  src/video_core/renderer_vulkan/vk_shader_gen.h
  src/video_core/renderer_vulkan/vk_shader_gen_spv.cpp
  src/video_core/renderer_vulkan/vk_shader_gen_spv.h
  src/video_core/shader/shader_uniforms.cpp
  src/video_core/shader/shader_uniforms.h
Labels: canary-merge

#6895 [ShaderGen] Avoid setting lighting states if components aren't enabled
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_vulkan/vk_shader_gen.cpp
Labels: canary-merge

#6887 build: Enable link time optimization in CI.
  .github/workflows/ci.yml
  CMakeLists.txt
  src/CMakeLists.txt
  src/audio_core/CMakeLists.txt
  src/common/CMakeLists.txt
  src/core/CMakeLists.txt
  src/input_common/CMakeLists.txt
  src/network/CMakeLists.txt
  src/video_core/CMakeLists.txt
  src/web_service/CMakeLists.txt
Labels: canary-merge

#6907 video_core: Avoid setting alpha tev with Dot3_RGBA8 color op
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_vulkan/vk_shader_gen.cpp
Labels: canary-merge

#6910 video_core: Correct shader interpeter address register handling.
  src/video_core/shader/shader_interpreter.cpp
Labels: canary-merge

#6921 tev: Use primary color for previous source in first stage
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_software/sw_rasterizer.cpp
  src/video_core/renderer_software/sw_rasterizer.h
  src/video_core/renderer_vulkan/vk_shader_gen.cpp
Labels: canary-merge

#6698 renderer_software: Multi-thread processing
  src/video_core/renderer_software/sw_framebuffer.cpp
  src/video_core/renderer_software/sw_framebuffer.h
  src/video_core/renderer_software/sw_rasterizer.cpp
  src/video_core/renderer_software/sw_rasterizer.h
Labels: F-gpu:sw-rasterizer

#6926 Port yuzu-emu/yuzu##11350: "fix: Added padding to reset defaults button"
  dist/qt_themes/default/style.qss
  dist/qt_themes/qdarkstyle_midnight_blue/style.qss
Labels: canary-merge

#6920 shader: Fix address register offset behavior in GLSL.
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge

#6925 video_core: Take factors into account with min/max blending functions
  externals/glad/include/glad/glad.h
  externals/glad/src/glad.c
  src/video_core/renderer_opengl/gl_driver.cpp
  src/video_core/renderer_opengl/gl_driver.h
  src/video_core/renderer_opengl/gl_rasterizer.cpp
  src/video_core/renderer_opengl/gl_rasterizer.h
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_opengl/gl_shader_gen.h
  src/video_core/renderer_opengl/gl_shader_manager.cpp
  src/video_core/renderer_opengl/gl_state.cpp
  src/video_core/renderer_opengl/gl_state.h
  src/video_core/renderer_opengl/pica_to_gl.h
  src/video_core/renderer_software/sw_framebuffer.cpp
  src/video_core/shader/shader_uniforms.cpp
  src/video_core/shader/shader_uniforms.h
Labels: canary-merge

#6937 shader: Fix shadow_texture_orthographic not being set correctly.
  src/video_core/renderer_opengl/gl_shader_gen.cpp
  src/video_core/renderer_vulkan/vk_shader_gen.cpp
Labels: canary-merge

#6935 gl_shader_decompiler: Fix min/max NaN edge case
  src/video_core/renderer_opengl/gl_shader_decompiler.cpp
Labels: canary-merge
